FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir dbt-postgres==1.8.2

COPY transforms ./transforms

ENV DBT_PROFILES_DIR=/app/transforms

CMD ["dbt", "run", "--project-dir", "/app/transforms", "--profiles-dir", "/app/transforms"]
