apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: dms
spec:
  selector:
    app: mealie
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: dms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.10.2
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: BASE_URL
              value: "http://192.5.87.69:30082"
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: dms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
